### ISSUE TITLE
Error opening talkgroups file.

### ISSUE THREAD

**Issue by samsonpwnz** [USA-RedDragon/trunk-recorder-soapysdrplay3#20]
Firstly, I appreciate work on getting this to work correctly with an Sdrplay. I am getting this error message with my talkgroups.csv, which works fine on the stock version of trunk-recorder.
trunk-recorder | [2023-12-07 02:42:59.506860] (info)   Loading Talkgroups...
trunk-recorder | [2023-12-07 02:42:59.506871] (info)   Reading Talkgroup CSV File: talkgroups.csv
trunk-recorder | [2023-12-07 02:42:59.506990] (error)   Failed parsing Config: Cannot open file talkgroups.csv

**Comment by samsonpwnz** [comment]
With the help of someone on the trunk-recorder discord, have figured this issue out.
Need to specify directory in config.json as /app/talkgroups.csv

**Comment by USA-RedDragon** [comment]
Hey, sorry for getting back on this too late. Glad you were able to find help!
